### ISSUE TITLE
Support for node.js requires

### ISSUE THREAD

**Issue by gramster** [axmor/typecs#45]
We have a node.js project that uses require for dependencies specified in a package.json file and thus installed in a node_modules directory.

This works when we compile from the command line, but when using typecs in Eclipse we get errors.

```
import express = require('express');
import http = require('http');
```

The first dependency (express) is in the package.json file and the node_modules directory; the second (http) is internal to node.

The errors are "Cannot find external module 'foo'"

It would be great if this was supported.

**Comment by basarat** [comment]
> This works when we compile from the command line

Using tsc?. 

I suspect you have `node.d.ts` referenced when you are compiling?

@axmor The fix here would be for @gramster to `/// reference` `node.d.ts` but I recommend that we start supporting `tsconfig.json` as the compilation context unit : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md

**Comment by gramster** [comment]
Yes, the file that has the errors starts with:

```
/// <reference path="../../../../externs/ts/node/node.d.ts" />
/// <reference path="../../../../externs/ts/express/express.d.ts" />
/// <reference path="../../../../externs/ts/node/nomnom.d.ts" />
/// <reference path="../../../../externs/ts/node/socket.io.d.ts" /> 
import config = require('./app/config');
import express = require('express');
import http = require('http');
```

with those last two imports being among the lines causing errors.

**Comment by kosz78** [comment]
@gramster I try the following example and it works fine:

```
/// <reference path="../externs/node/node.d.ts"/>
/// <reference path="../externs/express/express.d.ts"/>

var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

var server = app.listen(3000, function () {

  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);

});
```

Could you please check that compilation options set to use CommonJS modules
![image](https://cloud.githubusercontent.com/assets/3992195/7304307/67e5ab32-ea18-11e4-94b1-5643c1bd41e4.png)

**Comment by kosz78** [comment]
It also work in NodeJS notation:

```
/// <reference path="../externs/node/node.d.ts"/>
/// <reference path="../externs/express/express.d.ts"/>

import express = require('express');
import http = require('http');

var app: express.Application = express();

app.get('/', function (req: express.Request, res: express.Response) {
  res.send('Hello World!');
});

var server = app.listen(3000, function () {

  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);

});
```

**Comment by gramster** [comment]
Yes, I have commonjs as the module type. Does not work for me. I have two
projects, one of which works, and the main difference seems to be that in
the one that works the scripts are nested one directory down in the project
directory, while in the other they are in the root of the project directory.

**Comment by gramster** [comment]
(Clarifying last mail) So in the project that works I have 'scripts' in the
'Source directory or file' field in the Typescript project settings. In the
one that doesn't work I have either blank or I've tried '.'. Either way
this seems to be an issue and I get a popup:

Errors occurred during the build.

Errors running builder 'Typescript Project Builder' on project 'Foo'.

Path must include project and resource name: /Foo

And then I get errors marked in the editor where I do these require()
calls. So that may be the underlying problem.

**Comment by kosz78** [comment]
Path problem was fixed in the latest commit https://drone.io/github.com/axmor/typecs/files

**Comment by gramster** [comment]
Can you clarify what you mean by this? I still have a problem.

**Comment by kosz78** [comment]
@gramster I have tested the latest dev build with the file in root folder it also works:
![image](https://cloud.githubusercontent.com/assets/3992195/7477637/fcb834a2-f376-11e4-9c4c-31c6457de146.png)
